global_defs {
  router_id MASTER_NODE
  enable_script_security
}

vrrp_script check_web {
  script "/usr/local/bin/check_web.sh 80 /var/www/html"
  user root
  interval 3
  timeout 2
  fall 1
  rise 1
  weight -200
}

vrrp_instance VI_1 {
  state MASTER
  interface @IFACE@
  virtual_router_id 15
  priority 150
  advert_int 1

  unicast_src_ip @SRC_IP@
  unicast_peer {
    @PEER_IP@
  }

  virtual_ipaddress {
    192.168.56.15/24
  }

  track_script {
    check_web
  }
}

